config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/add_venda'
  post 'home/create_venda'

  resources :vendas
  resources :vendedors
  resources :clientes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/venda.rb
class Venda < ApplicationRecord
end

app/models/vendedor.rb
class Vendedor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :score)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token


  def index
  end

  def add_venda
    @clientes = Cliente.all
    @vendedores = Vendedor.all
  end

  def create_venda

    # Recebe os dados
    cliente_id = params[:cliente_id]
    vendedor_id = params[:vendedor_id]
    item = params[:item]
    total = params[:total]

    # Exemplo de código dinâmico
    a = "string"
    b = 4
    c = 23.78

    # Verificações...
    if(cliente_id == 0 || vendedor_id == 0 || item == '' || total == '')
      redirect_to(controller: 'home', action: 'index')
    end

    # Cria o objeto venda...
    venda = Venda.new(cliente_id: cliente_id, vendedor_id: vendedor_id, item: item, total: total)
    
    # Save...
    if(venda.save)
      redirect_to(controller: 'home', action: 'index')
    end

  end
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: [:show, :edit, :update, :destroy]

  # GET /vendas
  # GET /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1
  # GET /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @venda = Venda.new
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas
  # POST /vendas.json
  def create
    @venda = Venda.new(venda_params)

    respond_to do |format|
      if @venda.save
        format.html { redirect_to @venda, notice: 'Venda was successfully created.' }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1
  # PATCH/PUT /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to @venda, notice: 'Venda was successfully updated.' }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1
  # DELETE /vendas/1.json
  def destroy
    @venda.destroy
    respond_to do |format|
      format.html { redirect_to vendas_url, notice: 'Venda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venda_params
      params.require(:venda).permit(:item, :total, :cliente_id, :vendedor_id)
    end
end

app/controllers/vendedors_controller.rb
class VendedorsController < ApplicationController
  before_action :set_vendedor, only: [:show, :edit, :update, :destroy]

  # GET /vendedors
  # GET /vendedors.json
  def index
    @vendedors = Vendedor.all
  end

  # GET /vendedors/1
  # GET /vendedors/1.json
  def show
  end

  # GET /vendedors/new
  def new
    @vendedor = Vendedor.new
  end

  # GET /vendedors/1/edit
  def edit
  end

  # POST /vendedors
  # POST /vendedors.json
  def create
    @vendedor = Vendedor.new(vendedor_params)

    respond_to do |format|
      if @vendedor.save
        format.html { redirect_to @vendedor, notice: 'Vendedor was successfully created.' }
        format.json { render :show, status: :created, location: @vendedor }
      else
        format.html { render :new }
        format.json { render json: @vendedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendedors/1
  # PATCH/PUT /vendedors/1.json
  def update
    respond_to do |format|
      if @vendedor.update(vendedor_params)
        format.html { redirect_to @vendedor, notice: 'Vendedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendedor }
      else
        format.html { render :edit }
        format.json { render json: @vendedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendedors/1
  # DELETE /vendedors/1.json
  def destroy
    @vendedor.destroy
    respond_to do |format|
      format.html { redirect_to vendedors_url, notice: 'Vendedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendedor
      @vendedor = Vendedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendedor_params
      params.require(:vendedor).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/helpers/vendedors_helper.rb
module VendedorsHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.score %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Score:</strong>
  <%= @cliente.score %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/home/add_venda.html.erb
<h1>Adicionar nova venda</h1>

<form method="POST" action="/home/create_venda">
    <select name="cliente_id">
        <option value="0">Selecione o cliente</option>

        <% @clientes.each do |cliente| %>
            <option value="<%= cliente.id %>"><%= cliente.nome %></option>
        <% end %>
    </select>

    <select name="vendedor_id">
        <option value="0">Selecione o vendedor</option>
        
        <% @vendedores.each do |vendedor| %>
            <option value="<%= vendedor.id %>"><%= vendedor.nome %></option>
        <% end %>
    </select>

    <input type="text" name="item" placeholder="Nome do item" />
    <input type="text" name="total" placeholder="Total" />

    <button type="submit">Nova venda</button>
</form>

app/views/home/index.html.erb
<h1>Dashboard</h1>

<a href="/clientes"><button type="button">Verificar clientes</button></a>
<a href="/vendedors"><button type="button">Verificar vendedores</button></a>
<a href="/vendas"><button type="button">Verificar vendas</button></a>

<br /><br />

<a href="/home/add_venda"><button type="button">Nova venda</button></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vendas/_form.html.erb
<%= form_with(model: venda, local: true) do |form| %>
  <% if venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venda.errors.count, "error") %> prohibited this venda from being saved:</h2>

      <ul>
        <% venda.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="field">
    <%= form.label :cliente_id %>
    <%= form.number_field :cliente_id %>
  </div>

  <div class="field">
    <%= form.label :vendedor_id %>
    <%= form.number_field :vendedor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vendas/edit.html.erb
<h1>Editing Venda</h1>

<%= render 'form', venda: @venda %>

<%= link_to 'Show', @venda %> |
<%= link_to 'Back', vendas_path %>

app/views/vendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendas</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Total</th>
      <th>Cliente</th>
      <th>Vendedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendas.each do |venda| %>
      <tr>
        <td><%= venda.item %></td>
        <td><%= venda.total %></td>
        <td><%= venda.cliente_id %></td>
        <td><%= venda.vendedor_id %></td>
        <td><%= link_to 'Show', venda %></td>
        <td><%= link_to 'Edit', edit_venda_path(venda) %></td>
        <td><%= link_to 'Destroy', venda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venda', new_venda_path %>

app/views/vendas/new.html.erb
<h1>New Venda</h1>

<%= render 'form', venda: @venda %>

<%= link_to 'Back', vendas_path %>

app/views/vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @venda.item %>
</p>

<p>
  <strong>Total:</strong>
  <%= @venda.total %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @venda.cliente_id %>
</p>

<p>
  <strong>Vendedor:</strong>
  <%= @venda.vendedor_id %>
</p>

<%= link_to 'Edit', edit_venda_path(@venda) %> |
<%= link_to 'Back', vendas_path %>

app/views/vendedors/_form.html.erb
<%= form_with(model: vendedor, local: true) do |form| %>
  <% if vendedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendedor.errors.count, "error") %> prohibited this vendedor from being saved:</h2>

      <ul>
        <% vendedor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vendedors/edit.html.erb
<h1>Editing Vendedor</h1>

<%= render 'form', vendedor: @vendedor %>

<%= link_to 'Show', @vendedor %> |
<%= link_to 'Back', vendedors_path %>

app/views/vendedors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendedores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendedors.each do |vendedor| %>
      <tr>
        <td><%= vendedor.nome %></td>
        <td><%= link_to 'Show', vendedor %></td>
        <td><%= link_to 'Edit', edit_vendedor_path(vendedor) %></td>
        <td><%= link_to 'Destroy', vendedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendedor', new_vendedor_path %>

app/views/vendedors/new.html.erb
<h1>New Vendedor</h1>

<%= render 'form', vendedor: @vendedor %>

<%= link_to 'Back', vendedors_path %>

app/views/vendedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @vendedor.nome %>
</p>

<%= link_to 'Edit', edit_vendedor_path(@vendedor) %> |
<%= link_to 'Back', vendedors_path %>